"""
BF Messaging Server
===================
asyncio TCP server on port 9999.  Clients speak the BF Messaging Protocol,
which is generated by the Brainfuck command-builder programs.

Protocol (newline-terminated text)
-----------------------------------
Client → Server:
  REGISTER <username>
  FIND <username>
  SEND <to_username> <message text>
  HISTORY <with_username>
  QUIT

Server → Client:
  +OK <info>
  -ERR <reason>
  +USER <username> online|offline
  +INCOMING <from> <ISO-timestamp> <message>   ← pushed asynchronously
  +HIST <from> <ISO-timestamp> <message>        ← repeated, then:
  +END
"""

import asyncio
import sqlite3
import datetime
import os
import sys

HOST = "0.0.0.0"
PORT = 9999
DB_PATH = os.path.join(os.path.dirname(__file__), "messages.db")

# username → StreamWriter for currently connected, registered clients
connected_clients: dict[str, asyncio.StreamWriter] = {}

# ---------------------------------------------------------------------------
# Database helpers  (SQLite is fine here – asyncio is single-threaded, so no
# concurrent writes ever overlap)
# ---------------------------------------------------------------------------

_db_conn: sqlite3.Connection | None = None


def db() -> sqlite3.Connection:
    global _db_conn
    if _db_conn is None:
        _db_conn = sqlite3.connect(DB_PATH, check_same_thread=False)
        _db_conn.row_factory = sqlite3.Row
    return _db_conn


def init_db() -> None:
    c = db().cursor()
    c.executescript("""
        CREATE TABLE IF NOT EXISTS users (
            id         INTEGER PRIMARY KEY AUTOINCREMENT,
            username   TEXT    UNIQUE NOT NULL,
            created_at TEXT    NOT NULL
        );

        CREATE TABLE IF NOT EXISTS messages (
            id         INTEGER PRIMARY KEY AUTOINCREMENT,
            from_user  TEXT NOT NULL,
            to_user    TEXT NOT NULL,
            content    TEXT NOT NULL,
            ts         TEXT NOT NULL
        );
    """)
    db().commit()


def now_iso() -> str:
    return datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S")


# ---------------------------------------------------------------------------
# Per-client handler
# ---------------------------------------------------------------------------

async def handle_client(
    reader: asyncio.StreamReader,
    writer: asyncio.StreamWriter,
) -> None:
    addr = writer.get_extra_info("peername")
    username: str | None = None

    async def send(line: str) -> None:
        try:
            writer.write((line + "\n").encode())
            await writer.drain()
        except Exception:
            pass

    print(f"[+] Connection from {addr}")

    try:
        while True:
            raw = await reader.readline()
            if not raw:
                break  # client disconnected

            line = raw.decode(errors="replace").strip()
            if not line:
                continue

            # Split into at most 3 parts so message text is kept intact
            parts = line.split(" ", 2)
            cmd = parts[0].upper()

            # ----------------------------------------------------------------
            if cmd == "REGISTER":
                if len(parts) < 2:
                    await send("-ERR REGISTER requires a username")
                    continue

                uname = parts[1].strip()
                if not uname.isalnum():
                    await send("-ERR Username must be alphanumeric")
                    continue

                c = db().cursor()
                c.execute(
                    "INSERT OR IGNORE INTO users (username, created_at) VALUES (?, ?)",
                    (uname, now_iso()),
                )
                db().commit()

                # Log out any previous session for this username
                if uname in connected_clients:
                    try:
                        connected_clients[uname].write(b"+OK Your session was taken over\n")
                        await connected_clients[uname].drain()
                        connected_clients[uname].close()
                    except Exception:
                        pass

                username = uname
                connected_clients[username] = writer
                rows_changed = c.rowcount
                verb = "Registered" if rows_changed else "Welcome back"
                await send(f"+OK {verb} as {username}")
                print(f"    [{username}] registered from {addr}")

            # ----------------------------------------------------------------
            elif cmd == "FIND":
                if len(parts) < 2:
                    await send("-ERR FIND requires a username")
                    continue

                target = parts[1].strip()
                c = db().cursor()
                c.execute("SELECT username FROM users WHERE username = ?", (target,))
                row = c.fetchone()

                if row:
                    status = "online" if target in connected_clients else "offline"
                    await send(f"+USER {target} {status}")
                else:
                    await send(f"-ERR User '{target}' not found")

            # ----------------------------------------------------------------
            elif cmd == "SEND":
                if not username:
                    await send("-ERR You must REGISTER before sending messages")
                    continue
                if len(parts) < 3:
                    await send("-ERR Usage: SEND <to_username> <message>")
                    continue

                to_user = parts[1].strip()
                message = parts[2]

                if to_user == username:
                    await send("-ERR You cannot message yourself")
                    continue

                c = db().cursor()
                c.execute(
                    "SELECT username FROM users WHERE username = ?", (to_user,)
                )
                if not c.fetchone():
                    await send(f"-ERR User '{to_user}' not found")
                    continue

                ts = now_iso()
                c.execute(
                    "INSERT INTO messages (from_user, to_user, content, ts) VALUES (?, ?, ?, ?)",
                    (username, to_user, message, ts),
                )
                db().commit()

                # Push to recipient if online (best-effort)
                if to_user in connected_clients:
                    try:
                        connected_clients[to_user].write(
                            f"+INCOMING {username} {ts} {message}\n".encode()
                        )
                        await connected_clients[to_user].drain()
                    except Exception:
                        pass

                await send(f"+OK Message delivered to {to_user}")
                print(f"    [{username}] → [{to_user}]: {message!r}")

            # ----------------------------------------------------------------
            elif cmd == "HISTORY":
                if not username:
                    await send("-ERR You must REGISTER first")
                    continue
                if len(parts) < 2:
                    await send("-ERR HISTORY requires a username")
                    continue

                with_user = parts[1].strip()
                c = db().cursor()
                c.execute(
                    """
                    SELECT from_user, to_user, content, ts
                    FROM messages
                    WHERE (from_user = ? AND to_user = ?)
                       OR (from_user = ? AND to_user = ?)
                    ORDER BY id ASC
                    LIMIT 100
                    """,
                    (username, with_user, with_user, username),
                )
                rows = c.fetchall()

                if not rows:
                    await send(f"+END No messages with {with_user}")
                else:
                    for row in rows:
                        await send(f"+HIST {row['from_user']} {row['ts']} {row['content']}")
                    await send("+END")

            # ----------------------------------------------------------------
            elif cmd == "QUIT":
                await send("+OK Goodbye")
                break

            # ----------------------------------------------------------------
            else:
                await send(f"-ERR Unknown command '{cmd}'")

    except asyncio.IncompleteReadError:
        pass
    except Exception as exc:
        print(f"[!] Error from {addr}: {exc}", file=sys.stderr)
    finally:
        if username and connected_clients.get(username) is writer:
            del connected_clients[username]
        writer.close()
        try:
            await writer.wait_closed()
        except Exception:
            pass
        print(f"[-] {username or addr} disconnected")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

async def main() -> None:
    init_db()
    server = await asyncio.start_server(handle_client, HOST, PORT)
    addrs = ", ".join(str(s.getsockname()) for s in server.sockets)
    print(f"BF Messaging Server listening on {addrs}")
    print("Ctrl-C to stop.\n")
    async with server:
        await server.serve_forever()


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("\nServer stopped.")
