"""
BF Messaging Server
===================
asyncio TCP server with automatic port fallback (tries 9999, then 10000+).
Clients speak the BF Messaging Protocol, generated by Brainfuck programs.

Protocol (newline-terminated text)
-----------------------------------
1:1 Messaging:
  Client → Server:
    REGISTER <username>
    FIND <username>
    SEND <to_username> <message text>
    HISTORY <with_username>

Group Messaging:
  Client → Server:
    CREATE GROUP <groupname>
    JOIN GROUP <groupname>
    LEAVE GROUP <groupname>
    SEND TO GROUP <groupname> <message>
    LIST GROUPS
    GROUP MEMBERS <groupname>

Both:
  Client → Server:
    QUIT

Server → Client:
  +OK <info>
  -ERR <reason>
  +USER <username> online|offline
  +INCOMING <from> <ISO-timestamp> <message>           ← pushed 1:1
  +INCOMING GROUP <groupname> <from> <ISO-timestamp> <message>  ← pushed group
  +HIST <from> <ISO-timestamp> <message>                ← history 1:1
  +GROUP <groupname> <member_list>                      ← group created/joined
  +NEW_GROUP <groupname>                                ← pushed when added to a group
  +MEMBERS <groupname> <member1> <member2> ...          ← list response
  +END
"""

import asyncio
import sqlite3
import datetime
import os
import sys

HOST = "0.0.0.0"
DEFAULT_PORT = 9999
MAX_PORT_TRIES = 20
DB_PATH = os.path.join(os.path.dirname(__file__), "messages.db")

# username → StreamWriter for currently connected, registered clients
connected_clients: dict[str, asyncio.StreamWriter] = {}

# groupname → set of usernames currently subscribed to that group
group_subscribers: dict[str, set[str]] = {}

# ---------------------------------------------------------------------------
# Database helpers  (SQLite is fine here – asyncio is single-threaded, so no
# concurrent writes ever overlap)
# ---------------------------------------------------------------------------

_db_conn: sqlite3.Connection | None = None


def db() -> sqlite3.Connection:
    global _db_conn
    if _db_conn is None:
        _db_conn = sqlite3.connect(DB_PATH, check_same_thread=False)
        _db_conn.row_factory = sqlite3.Row
    return _db_conn


def init_db() -> None:
    c = db().cursor()
    c.executescript("""
        CREATE TABLE IF NOT EXISTS users (
            id           INTEGER PRIMARY KEY AUTOINCREMENT,
            username     TEXT    UNIQUE NOT NULL,
            created_at   TEXT    NOT NULL,
            last_seen_at TEXT
        );

        CREATE TABLE IF NOT EXISTS messages (
            id         INTEGER PRIMARY KEY AUTOINCREMENT,
            from_user  TEXT NOT NULL,
            to_user    TEXT NOT NULL,
            content    TEXT NOT NULL,
            ts         TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS groups (
            id         INTEGER PRIMARY KEY AUTOINCREMENT,
            groupname  TEXT    UNIQUE NOT NULL,
            created_by TEXT    NOT NULL,
            created_at TEXT    NOT NULL
        );

        CREATE TABLE IF NOT EXISTS group_members (
            id        INTEGER PRIMARY KEY AUTOINCREMENT,
            groupname TEXT NOT NULL,
            username  TEXT NOT NULL,
            joined_at TEXT NOT NULL,
            UNIQUE(groupname, username)
        );

        CREATE TABLE IF NOT EXISTS group_messages (
            id         INTEGER PRIMARY KEY AUTOINCREMENT,
            groupname  TEXT NOT NULL,
            from_user  TEXT NOT NULL,
            content    TEXT NOT NULL,
            ts         TEXT NOT NULL
        );
    """)
    db().commit()
    # Safe migration: add last_seen_at if the DB was created before this column existed
    try:
        c.execute("ALTER TABLE users ADD COLUMN last_seen_at TEXT")
        db().commit()
    except sqlite3.OperationalError:
        pass  # Column already exists


def now_iso() -> str:
    return datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%S")


# ---------------------------------------------------------------------------
# Per-client handler
# ---------------------------------------------------------------------------

async def handle_client(
    reader: asyncio.StreamReader,
    writer: asyncio.StreamWriter,
) -> None:
    addr = writer.get_extra_info("peername")
    username: str | None = None

    async def send(line: str) -> None:
        try:
            writer.write((line + "\n").encode())
            await writer.drain()
        except Exception:
            pass

    print(f"[+] Connection from {addr}")

    try:
        while True:
            raw = await reader.readline()
            if not raw:
                break  # client disconnected

            line = raw.decode(errors="replace").strip()
            if not line:
                continue

            # Split into at most 3 parts so message text is kept intact
            parts = line.split(" ", 2)
            cmd = parts[0].upper()

            # ----------------------------------------------------------------
            if cmd == "REGISTER":
                if len(parts) < 2:
                    await send("-ERR REGISTER requires a username")
                    continue

                uname = parts[1].strip()
                if not uname.isalnum():
                    await send("-ERR Username must be alphanumeric")
                    continue

                c = db().cursor()

                # Capture last_seen_at BEFORE the upsert so we know when they were last online
                c.execute("SELECT last_seen_at FROM users WHERE username = ?", (uname,))
                row = c.fetchone()
                last_seen = row["last_seen_at"] if row else None

                c.execute(
                    "INSERT OR IGNORE INTO users (username, created_at) VALUES (?, ?)",
                    (uname, now_iso()),
                )
                db().commit()

                # Log out any previous session for this username
                if uname in connected_clients:
                    try:
                        connected_clients[uname].write(b"+OK Your session was taken over\n")
                        await connected_clients[uname].drain()
                        connected_clients[uname].close()
                    except Exception:
                        pass

                username = uname
                connected_clients[username] = writer

                # Restore this user's group subscriptions from DB so live
                # pushes work whether they joined before or after server restart
                c.execute(
                    "SELECT groupname FROM group_members WHERE username = ?",
                    (username,),
                )
                for grow in c.fetchall():
                    grp = grow["groupname"]
                    if grp not in group_subscribers:
                        group_subscribers[grp] = set()
                    group_subscribers[grp].add(username)

                rows_changed = c.rowcount
                verb = "Registered" if rows_changed else "Welcome back"
                await send(f"+OK {verb} as {username}")
                print(f"    [{username}] registered from {addr}")

                # Push missed messages (sent while offline) as live push lines
                if last_seen:
                    c.execute(
                        "SELECT from_user, content, ts FROM messages"
                        " WHERE to_user = ? AND ts >= ? ORDER BY ts ASC LIMIT 200",
                        (username, last_seen),
                    )
                    for msg in c.fetchall():
                        await send(f"+INCOMING {msg['from_user']} {msg['ts']} {msg['content']}")

                    c.execute(
                        "SELECT gm.groupname, gm.from_user, gm.content, gm.ts"
                        " FROM group_messages gm"
                        " JOIN group_members mb ON gm.groupname = mb.groupname AND mb.username = ?"
                        " WHERE gm.ts >= ? AND gm.from_user != ? ORDER BY gm.ts ASC LIMIT 200",
                        (username, last_seen, username),
                    )
                    for msg in c.fetchall():
                        await send(
                            f"+INCOMING GROUP {msg['groupname']} {msg['from_user']}"
                            f" {msg['ts']} {msg['content']}"
                        )

            # ----------------------------------------------------------------
            elif cmd == "FIND":
                if len(parts) < 2:
                    await send("-ERR FIND requires a username")
                    continue

                target = parts[1].strip()
                c = db().cursor()
                c.execute("SELECT username FROM users WHERE username = ?", (target,))
                row = c.fetchone()

                if row:
                    status = "online" if target in connected_clients else "offline"
                    await send(f"+USER {target} {status}")
                else:
                    await send(f"-ERR User '{target}' not found")

            # ----------------------------------------------------------------
            elif cmd == "HISTORY":
                if not username:
                    await send("-ERR You must REGISTER first")
                    continue
                if len(parts) < 2:
                    await send("-ERR HISTORY requires a username")
                    continue

                with_user = parts[1].strip()
                c = db().cursor()
                c.execute(
                    """
                    SELECT from_user, to_user, content, ts
                    FROM messages
                    WHERE (from_user = ? AND to_user = ?)
                       OR (from_user = ? AND to_user = ?)
                    ORDER BY id ASC
                    LIMIT 100
                    """,
                    (username, with_user, with_user, username),
                )
                rows = c.fetchall()

                if not rows:
                    await send(f"+END No messages with {with_user}")
                else:
                    for row in rows:
                        await send(f"+HIST {row['from_user']} {row['ts']} {row['content']}")
                    await send("+END")

            # ----------------------------------------------------------------
            elif cmd == "CREATE":
                if not username:
                    await send("-ERR You must REGISTER first")
                    continue
                if len(parts) < 3 or parts[1].upper() != "GROUP":
                    await send("-ERR Usage: CREATE GROUP <groupname>")
                    continue

                groupname = parts[2].strip()
                if not groupname.replace("_", "").isalnum():
                    await send("-ERR Group name must be alphanumeric (underscores OK)")
                    continue

                c = db().cursor()
                try:
                    c.execute(
                        "INSERT INTO groups (groupname, created_by, created_at) VALUES (?, ?, ?)",
                        (groupname, username, now_iso()),
                    )
                    c.execute(
                        "INSERT INTO group_members (groupname, username, joined_at) VALUES (?, ?, ?)",
                        (groupname, username, now_iso()),
                    )
                    db().commit()
                    group_subscribers[groupname] = {username}
                    await send(f"+GROUP {groupname} {username}")
                    print(f"    [{username}] created group [{groupname}]")
                except sqlite3.IntegrityError:
                    await send(f"-ERR Group '{groupname}' already exists")

            # ----------------------------------------------------------------
            elif cmd == "JOIN":
                if not username:
                    await send("-ERR You must REGISTER first")
                    continue
                if len(parts) < 3 or parts[1].upper() != "GROUP":
                    await send("-ERR Usage: JOIN GROUP <groupname>")
                    continue

                groupname = parts[2].strip()
                c = db().cursor()
                c.execute("SELECT groupname FROM groups WHERE groupname = ?", (groupname,))
                if not c.fetchone():
                    await send(f"-ERR Group '{groupname}' not found")
                    continue

                try:
                    c.execute(
                        "INSERT INTO group_members (groupname, username, joined_at) VALUES (?, ?, ?)",
                        (groupname, username, now_iso()),
                    )
                    db().commit()
                    if groupname not in group_subscribers:
                        group_subscribers[groupname] = set()
                    group_subscribers[groupname].add(username)
                    await send(f"+OK Joined group {groupname}")
                    print(f"    [{username}] joined [{groupname}]")
                except sqlite3.IntegrityError:
                    await send(f"-ERR Already a member of {groupname}")

            # ----------------------------------------------------------------
            elif cmd == "LEAVE":
                if not username:
                    await send("-ERR You must REGISTER first")
                    continue
                if len(parts) < 3 or parts[1].upper() != "GROUP":
                    await send("-ERR Usage: LEAVE GROUP <groupname>")
                    continue

                groupname = parts[2].strip()
                c = db().cursor()
                c.execute(
                    "DELETE FROM group_members WHERE groupname = ? AND username = ?",
                    (groupname, username),
                )
                if c.rowcount == 0:
                    await send(f"-ERR Not a member of {groupname}")
                else:
                    db().commit()
                    if groupname in group_subscribers:
                        group_subscribers[groupname].discard(username)
                    await send(f"+OK Left group {groupname}")
                    print(f"    [{username}] left [{groupname}]")

            # ----------------------------------------------------------------
            elif cmd == "ADD":
                if not username:
                    await send("-ERR You must REGISTER first")
                    continue
                # ADD MEMBER <groupname> <target_username>
                if len(parts) < 3 or parts[1].upper() != "MEMBER":
                    await send("-ERR Usage: ADD MEMBER <groupname> <username>")
                    continue

                rest2 = parts[2].strip().split(" ", 1)
                if len(rest2) < 2:
                    await send("-ERR Usage: ADD MEMBER <groupname> <username>")
                    continue
                groupname, target = rest2[0].strip(), rest2[1].strip()

                c = db().cursor()

                # Caller must be a group member
                c.execute(
                    "SELECT username FROM group_members WHERE groupname = ? AND username = ?",
                    (groupname, username),
                )
                if not c.fetchone():
                    await send(f"-ERR You are not a member of {groupname}")
                    continue

                # Target user must exist
                c.execute("SELECT username FROM users WHERE username = ?", (target,))
                if not c.fetchone():
                    await send(f"-ERR User '{target}' not found")
                    continue

                try:
                    c.execute(
                        "INSERT INTO group_members (groupname, username, joined_at) VALUES (?, ?, ?)",
                        (groupname, target, now_iso()),
                    )
                    db().commit()
                    if groupname not in group_subscribers:
                        group_subscribers[groupname] = set()
                    group_subscribers[groupname].add(target)
                    await send(f"+OK Added {target} to {groupname}")
                    print(f"    [{username}] added [{target}] to [{groupname}]")
                    # Notify target if online
                    if target in connected_clients:
                        try:
                            connected_clients[target].write(
                                f"+NEW_GROUP {groupname}\n".encode()
                            )
                            await connected_clients[target].drain()
                        except Exception:
                            pass
                except sqlite3.IntegrityError:
                    await send(f"-ERR {target} is already a member of {groupname}")

            # ----------------------------------------------------------------
            elif cmd == "SEND":
                if not username:
                    await send("-ERR You must REGISTER before sending messages")
                    continue

                # Robustly detect group sends by inspecting the full line
                # Expected: "SEND TO GROUP <groupname> <message>"
                if line.upper().startswith("SEND TO GROUP "):
                    rest = line[len("SEND TO GROUP "):].lstrip()
                    if not rest:
                        await send("-ERR Usage: SEND TO GROUP <groupname> <message>")
                        continue

                    parts2 = rest.split(" ", 1)
                    groupname = parts2[0].strip()
                    message = parts2[1].strip() if len(parts2) > 1 else ""

                    if not message:
                        await send("-ERR Message cannot be empty")
                        continue

                    c = db().cursor()
                    c.execute("SELECT groupname FROM groups WHERE groupname = ?", (groupname,))
                    if not c.fetchone():
                        await send(f"-ERR Group '{groupname}' not found")
                        continue

                    c.execute(
                        "SELECT username FROM group_members WHERE groupname = ? AND username = ?",
                        (groupname, username),
                    )
                    if not c.fetchone():
                        await send(f"-ERR You are not a member of {groupname}")
                        continue

                    ts = now_iso()
                    c.execute(
                        "INSERT INTO group_messages (groupname, from_user, content, ts) VALUES (?, ?, ?, ?)",
                        (groupname, username, message, ts),
                    )
                    db().commit()

                    # Push to all online group members
                    for member in group_subscribers.get(groupname, set()):
                        if member in connected_clients:
                            try:
                                connected_clients[member].write(
                                    f"+INCOMING GROUP {groupname} {username} {ts} {message}\n".encode()
                                )
                                await connected_clients[member].drain()
                            except Exception:
                                pass

                    await send(f"+OK Message sent to group {groupname}")
                    print(f"    [{username}] → GROUP [{groupname}]: {message!r}")
                else:
                    # SEND <to_username> <message>
                    if len(parts) < 3:
                        await send("-ERR Usage: SEND <to_username> <message>")
                        continue

                    to_user = parts[1].strip()
                    message = parts[2]

                    if to_user == username:
                        await send("-ERR You cannot message yourself")
                        continue

                    c = db().cursor()
                    c.execute(
                        "SELECT username FROM users WHERE username = ?", (to_user,)
                    )
                    if not c.fetchone():
                        await send(f"-ERR User '{to_user}' not found")
                        continue

                    ts = now_iso()
                    c.execute(
                        "INSERT INTO messages (from_user, to_user, content, ts) VALUES (?, ?, ?, ?)",
                        (username, to_user, message, ts),
                    )
                    db().commit()

                    # Push to recipient if online (best-effort)
                    if to_user in connected_clients:
                        try:
                            connected_clients[to_user].write(
                                f"+INCOMING {username} {ts} {message}\n".encode()
                            )
                            await connected_clients[to_user].drain()
                        except Exception:
                            pass

                    await send(f"+OK Message delivered to {to_user}")
                    print(f"    [{username}] → [{to_user}]: {message!r}")

            # ----------------------------------------------------------------
            elif cmd == "LIST":
                if not username:
                    await send("-ERR You must REGISTER first")
                    continue
                if len(parts) < 2:
                    await send("-ERR Usage: LIST GROUPS | LIST CHATS")
                    continue

                sub = parts[1].upper()

                if sub == "GROUPS":
                    c = db().cursor()
                    c.execute(
                        "SELECT DISTINCT g.groupname FROM groups g "
                        "INNER JOIN group_members gm ON g.groupname = gm.groupname "
                        "WHERE gm.username = ? ORDER BY g.groupname",
                        (username,),
                    )
                    rows = c.fetchall()
                    if not rows:
                        await send("+END You are not a member of any groups")
                    else:
                        for row in rows:
                            await send(f"+GROUP {row['groupname']}")
                        await send("+END")

                elif sub == "CHATS":
                    # Return distinct peers the user has exchanged messages with
                    c = db().cursor()
                    c.execute(
                        "SELECT DISTINCT"
                        " CASE WHEN from_user = ? THEN to_user ELSE from_user END AS peer"
                        " FROM messages WHERE from_user = ? OR to_user = ?"
                        " ORDER BY peer",
                        (username, username, username),
                    )
                    rows = c.fetchall()
                    if not rows:
                        await send("+END No conversations yet")
                    else:
                        for row in rows:
                            await send(f"+CHAT {row['peer']}")
                        await send("+END")

                else:
                    await send("-ERR Usage: LIST GROUPS | LIST CHATS")

            # ----------------------------------------------------------------
            elif cmd == "GROUP":
                if not username:
                    await send("-ERR You must REGISTER first")
                    continue
                if len(parts) < 3:
                    await send("-ERR Usage: GROUP MEMBERS <groupname> | GROUP HISTORY <groupname>")
                    continue

                sub = parts[1].upper()
                groupname = parts[2].strip()
                c = db().cursor()

                if sub == "MEMBERS":
                    c.execute(
                        "SELECT username FROM group_members WHERE groupname = ? ORDER BY username",
                        (groupname,),
                    )
                    rows = c.fetchall()
                    if not rows:
                        await send(f"-ERR Group '{groupname}' not found or empty")
                    else:
                        member_list = " ".join(row["username"] for row in rows)
                        await send(f"+MEMBERS {groupname} {member_list}")

                elif sub == "HISTORY":
                    c.execute(
                        "SELECT from_user, content, ts FROM group_messages"
                        " WHERE groupname = ? ORDER BY ts ASC LIMIT 100",
                        (groupname,),
                    )
                    rows = c.fetchall()
                    if not rows:
                        await send(f"+END No messages in {groupname}")
                    else:
                        for row in rows:
                            await send(f"+GHIST {row['from_user']} {row['ts']} {row['content']}")
                        await send("+END")

                else:
                    await send("-ERR Usage: GROUP MEMBERS <groupname> | GROUP HISTORY <groupname>")

            # ----------------------------------------------------------------
            elif cmd == "QUIT":
                await send("+OK Goodbye")
                break

            # ----------------------------------------------------------------
            else:
                await send(f"-ERR Unknown command '{cmd}'")

    except asyncio.IncompleteReadError:
        pass
    except Exception as exc:
        print(f"[!] Error from {addr}: {exc}", file=sys.stderr)
    finally:
        if username and connected_clients.get(username) is writer:
            del connected_clients[username]
        # Record when this user went offline for missed-message delivery next login
        if username:
            try:
                c2 = db().cursor()
                c2.execute(
                    "UPDATE users SET last_seen_at = ? WHERE username = ?",
                    (now_iso(), username),
                )
                db().commit()
            except Exception:
                pass
        writer.close()
        try:
            await writer.wait_closed()
        except Exception:
            pass
        print(f"[-] {username or addr} disconnected")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

async def main() -> None:
    init_db()
    port = DEFAULT_PORT
    server = None
    while port < DEFAULT_PORT + MAX_PORT_TRIES:
        try:
            server = await asyncio.start_server(handle_client, HOST, port)
            addrs = ", ".join(str(s.getsockname()) for s in server.sockets)
            print(f"BF Messaging Server listening on {addrs}")
            print("Ctrl-C to stop.\n")
            break
        except OSError as e:
            if "address already in use" in str(e).lower():
                port += 1
                continue
            raise
    if server is None:
        print(f"Could not find an available port (tried {DEFAULT_PORT} to {DEFAULT_PORT + MAX_PORT_TRIES - 1})")
        sys.exit(1)
    async with server:
        await server.serve_forever()


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("\nServer stopped.")
